apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof
spec:
  selector:
    matchLabels:
      app: goof
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: goof
        tier: frontend
    spec:
      containers:
        - name: goof
          image: gcr.io/bizdev-playground/gcp-goof:deploy #Edit with your GCP Project
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3001
          env:
            - name: DOCKER
              value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof-mongo
spec:
  selector:
    matchLabels:
      app: goof
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: goof
        tier: backend
    spec:
      containers:
        - name: goof-mongo
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: goof-lb
  labels:
    app: goof
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
    name: "goof-site"
  selector:
    app: goof
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: goof-mongo
  labels:
    app: goof
    tier: backend
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: "goof-db"
  selector:
    app: goof
    tier: backend
